name: klyseria
services:
  - name: web
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: your-username/klyseria
    build_command: npm run build
    run_command: npm run start
    envs:
      - key: WORDPRESS_API_URL
        scope: RUN_AND_BUILD_TIME
        value: ${WORDPRESS_API_URL}
      - key: NEXT_PUBLIC_SITE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${NEXT_PUBLIC_SITE_URL}
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
